# Generated by Django 4.2.7 on 2023-11-21 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userseg", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="department",
            new_name="deptid",
        ),
    ]
